live_config_reload = true

import = [
  "~/.config/alacritty/themes/dracula-pro-pro.toml"
]

[env]
# This needs to be screen-256color for tmux
TERM = "screen-256color"

[font]
size = 15.0
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]

[window]
startup_mode = "Fullscreen"
